### PR TITLE
Convert negative amplitude to int32 correctly

### PR DESCRIPTION
**Pull request by nathan-cormier**
Handle sign in wavfile bytes.

### CODE REVIEW

**Comment by cryptix** [comment]
thanks for this!

do you have a minimal wav file so I can see it for myself and add a test so that future-me also knows what is going on here?

**Comment by nathan-cormier** [comment]
Sure, here's a 2 second 55Hz tone, one of the files I was using during my work with your library.

[55Hz.wav.zip](https://github.com/cryptix/wav/files/975647/55Hz.wav.zip)

**Comment by cryptix** [comment]
Okay, got it and merged it in the `dontBreakTheSigns` branch.

Was pretty clear what was wrong from using plotWave on this. Audacity has some funky normalization going on, it seems...

Using your fix for the 24- and 32bit conversion does prompt a `go vet` warning though.

```
user@archTwo ~/g/s/g/c/wav> go vet reader.go 
reader.go:261: int16(s[2]) too small for shift of 16
reader.go:263: int16(s[2]) too small for shift of 16
reader.go:263: int16(s[3]) too small for shift of 24
```

Didn't have to do direct bit-fiddling recently... It looks like go doesn't zero pad them to a bigger size? 

Not sure this will break handling of these sample sizes so i'll hold of until we verified this.
Couldn't spend the time yet to construct a test.

**Comment by nathan-cormier** [comment]
Part of the problem is that AFAIK samples in a wav file may be either signed or unsigned depending on the encoder (https://trac.ffmpeg.org/wiki/audio%20types).

So to be correct here I guess ReadSample will have to handle both cases; it would need to be passed something from the header to indicate whether or not the data is signed I think.

For signed data, it can be parsed like this:
```
	case 1:
		n = int32(int8(s[0]))
	case 2:
		n = int32(int16(binary.LittleEndian.Uint16(s)))
 	case 3:
		// this will be more complicated, need to shift the bytes into a uint32
		// but then need to flip the sign bit accordingly, 
		// and reset the "false" sign bit that we shifted in
	case 4:
		n = int32(binary.LittleEndian.Uint32(s))
```

**Comment by nathan-cormier** [comment]
Closing for now, may revisit this later.

**Pull request closed without merging**
